[project]
name = "read4me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmitry Melnikov", email = "d.dash.mv@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cryptography>=3.1",
    "mutagen>=1.47.0",
    "openai>=2.20.0",
    "pillow>=12.1.1",
    "pymupdf>=1.27.1",
    "pypdf>=6.7.0",
    "python-dotenv>=1.2.1",
    "typer>=0.22.0",
]

[project.scripts]
read4me = "read4me:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
